import org.apache.hadoop.fs.{FileSystem, Path}
import org.apache.hadoop.conf._
import org.apache.spark.rdd.RDD
import org.apache.spark.{SparkConf, SparkContext}

import java.io.{BufferedReader, InputStreamReader}

object LanguageFrequency {
  def main(args: Array[String]): Unit = {
    val folder = if (args.length == 1) args.head else "books/*"
    // remove .setMaster("local[*]") in below line when running in cluster mode
    val sc = new SparkConf().setAppName("LanguageFrequency").setMaster("local[*]")
    val sparkContext = new SparkContext(sc)

    val hconf = sparkContext.hadoopConfiguration
    val hdfs = FileSystem.get(hconf)
    val files = hdfs.globStatus(new Path(folder)).map(_.getPath.toString)
    val result = doWork(sparkContext.parallelize(files))
    println(s"Most common language in directory: $result")
    sparkContext.stop()
  }

  def doWork(rdd: RDD[String]): String = {
    val books = rdd.map(file => {
      val hconf = new Configuration()
      val hdfs = FileSystem.get(hconf)
      val fin = new BufferedReader(new InputStreamReader(hdfs.open(new Path(file))))
      var line = fin.readLine()
      var englishCount: Long = 0
      var frenchCount: Long = 0
      var germanCount: Long = 0
      var total: Long = 0
      while (line != null) {
        val words = line.toLowerCase()
          .split(" ")
          .map(word => word.trim.replaceAll(".", "").replaceAll(",", ""))
          .filter(_.nonEmpty)
        for (word <- words) {
          if (englishWordsSet.contains(word)) englishCount += 1
          if (frenchWordsSet.contains(word)) frenchCount += 1
          if (germanWordsSet.contains(word)) germanCount += 1
        }
        total += words.length
        line = fin.readLine()
      }
      val bookLanguage = if (englishCount > frenchCount && englishCount > germanCount)
        "English"
      else if (frenchCount > germanCount)
        "French"
      else
        "German"
      (bookLanguage, total)
    })
    books
      .reduceByKey(_ + _)
      .sortBy(-_._2)
      .take(1)
      .head._1
  }

  val englishWordsSet: Set[String] =
    """
      |the
      |of
      |to
      |and
      |a
      |in
      |is
      |it
      |you
      |that
      |he
      |was
      |for
      |on
      |are
      |with
      |as
      |I
      |his
      |they
      |be
      |at
      |one
      |have
      |this
      |from
      |or
      |had
      |by
      |not
      |word
      |but
      |what
      |some
      |we
      |can
      |out
      |other
      |were
      |all
      |there
      |when
      |up
      |use
      |your
      |how
      |said
      |an
      |each
      |she
      |which
      |do
      |their
      |time
      |if
      |will
      |way
      |about
      |many
      |then
      |them
      |write
      |would
      |like
      |so
      |these
      |her
      |long
      |make
      |thing
      |see
      |him
      |two
      |has
      |look
      |more
      |day
      |could
      |go
      |come
      |did
      |number
      |sound
      |no
      |most
      |people
      |my
      |over
      |know
      |water
      |than
      |call
      |first
      |who
      |may
      |down
      |side
      |been
      |now
      |find
      |any
      |new
      |work
      |part
      |take
      |get
      |place
      |made
      |live
      |where
      |after
      |back
      |little
      |only
      |round
      |man
      |year
      |came
      |show
      |every
      |good
      |me
      |give
      |our
      |under
      |name
      |very
      |through
      |just
      |form
      |sentence
      |great
      |think
      |say
      |help
      |low
      |line
      |differ
      |turn
      |cause
      |much
      |mean
      |before
      |move
      |right
      |boy
      |old
      |too
      |same
      |tell
      |does
      |set
      |three
      |want
      |air
      |well
      |also
      |play
      |small
      |end
      |put
      |home
      |read
      |hand
      |port
      |large
      |spell
      |add
      |even
      |land
      |here
      |must
      |big
      |high
      |such
      |follow
      |act
      |why
      |ask
      |men
      |change
      |went
      |light
      |kind
      |off
      |need
      |house
      |picture
      |try
      |us
      |again
      |animal
      |point
      |mother
      |world
      |near
      |build
      |self
      |earth
      |father
      |head
      |stand
      |own
      |page
      |should
      |country
      |found
      |answer
      |school
      |grow
      |study
      |still
      |learn
      |plant
      |cover
      |food
      |sun
      |four
      |between
      |state
      |keep
      |eye
      |never
      |last
      |let
      |thought
      |city
      |tree
      |cross
      |farm
      |hard
      |start
      |might
      |story
      |saw
      |far
      |sea
      |draw
      |left
      |late
      |run
      |don't
      |while
      |press
      |close
      |night
      |real
      |life
      |few
      |north
      |open
      |seem
      |together
      |next
      |white
      |children
      |begin
      |got
      |walk
      |example
      |ease
      |paper
      |group
      |always
      |music
      |those
      |both
      |mark
      |often
      |letter
      |until
      |mile
      |river
      |car
      |feet
      |care
      |second
      |book
      |carry
      |took
      |science
      |eat
      |room
      |friend
      |began
      |idea
      |fish
      |mountain
      |stop
      |once
      |base
      |hear
      |horse
      |cut
      |sure
      |watch
      |color
      |face
      |wood
      |main
      |enough
      |plain
      |girl
      |usual
      |young
      |ready
      |above
      |ever
      |red
      |list
      |though
      |feel
      |talk
      |bird
      |soon
      |body
      |dog
      |family
      |direct
      |pose
      |leave
      |song
      |measure
      |door
      |product
      |black
      |short
      |numeral
      |class
      |wind
      |question
      |happen
      |complete
      |ship
      |area
      |half
      |rock
      |order
      |fire
      |south
      |problem
      |piece
      |told
      |knew
      |pass
      |since
      |top
      |whole
      |king
      |space
      |heard
      |best
      |hour
      |better
      |true
      |during
      |hundred
      |five
      |remember
      |step
      |early
      |hold
      |west
      |ground
      |interest
      |reach
      |fast
      |verb
      |sing
      |listen
      |six
      |table
      |travel
      |less
      |morning
      |ten
      |simple
      |several
      |vowel
      |toward
      |war
      |lay
      |against
      |pattern
      |slow
      |center
      |love
      |person
      |money
      |serve
      |appear
      |road
      |map
      |rain
      |rule
      |govern
      |pull
      |cold
      |notice
      |voice
      |unit
      |power
      |town
      |fine
      |certain
      |fly
      |fall
      |lead
      |cry
      |dark
      |machine
      |note
      |wait
      |plan
      |figure
      |star
      |box
      |noun
      |field
      |rest
      |correct
      |able
      |pound
      |done
      |beauty
      |drive
      |stood
      |contain
      |front
      |teach
      |week
      |final
      |gave
      |green
      |oh
      |quick
      |develop
      |ocean
      |warm
      |free
      |minute
      |strong
      |special
      |mind
      |behind
      |clear
      |tail
      |produce
      |fact
      |street
      |inch
      |multiply
      |nothing
      |course
      |stay
      |wheel
      |full
      |force
      |blue
      |object
      |decide
      |surface
      |deep
      |moon
      |island
      |foot
      |system
      |busy
      |test
      |record
      |boat
      |common
      |gold
      |possible
      |plane
      |stead
      |dry
      |wonder
      |laugh
      |thousand
      |ago
      |ran
      |check
      |game
      |shape
      |equate
      |hot
      |miss
      |brought
      |heat
      |snow
      |tire
      |bring
      |yes
      |distant
      |fill
      |east
      |paint
      |language
      |among
      |grand
      |ball
      |yet
      |wave
      |drop
      |heart
      |am
      |present
      |heavy
      |dance
      |engine
      |position
      |arm
      |wide
      |sail
      |material
      |size
      |vary
      |settle
      |speak
      |weight
      |general
      |ice
      |matter
      |circle
      |pair
      |include
      |divide
      |syllable
      |felt
      |perhaps
      |pick
      |sudden
      |count
      |square
      |reason
      |length
      |represent
      |art
      |subject
      |region
      |energy
      |hunt
      |probable
      |bed
      |brother
      |egg
      |ride
      |cell
      |believe
      |fraction
      |forest
      |sit
      |race
      |window
      |store
      |summer
      |train
      |sleep
      |prove
      |lone
      |leg
      |exercise
      |wall
      |catch
      |mount
      |wish
      |sky
      |board
      |joy
      |winter
      |sat
      |written
      |wild
      |instrument
      |kept
      |glass
      |grass
      |cow
      |job
      |edge
      |sign
      |visit
      |past
      |soft
      |fun
      |bright
      |gas
      |weather
      |month
      |million
      |bear
      |finish
      |happy
      |hope
      |flower
      |clothe
      |strange
      |gone
      |jump
      |baby
      |eight
      |village
      |meet
      |root
      |buy
      |raise
      |solve
      |metal
      |whether
      |push
      |seven
      |paragraph
      |third
      |shall
      |held
      |hair
      |describe
      |cook
      |floor
      |either
      |result
      |burn
      |hill
      |safe
      |cat
      |century
      |consider
      |type
      |law
      |bit
      |coast
      |copy
      |phrase
      |silent
      |tall
      |sand
      |soil
      |roll
      |temperature
      |finger
      |industry
      |value
      |fight
      |lie
      |beat
      |excite
      |natural
      |view
      |sense
      |ear
      |else
      |quite
      |broke
      |case
      |middle
      |kill
      |son
      |lake
      |moment
      |scale
      |loud
      |spring
      |observe
      |child
      |straight
      |consonant
      |nation
      |dictionary
      |milk
      |speed
      |method
      |organ
      |pay
      |age
      |section
      |dress
      |cloud
      |surprise
      |quiet
      |stone
      |tiny
      |climb
      |cool
      |design
      |poor
      |lot
      |experiment
      |bottom
      |key
      |iron
      |single
      |stick
      |flat
      |twenty
      |skin
      |smile
      |crease
      |hole
      |trade
      |melody
      |trip
      |office
      |receive
      |row
      |mouth
      |exact
      |symbol
      |die
      |least
      |trouble
      |shout
      |except
      |wrote
      |seed
      |tone
      |join
      |suggest
      |clean
      |break
      |lady
      |yard
      |rise
      |bad
      |blow
      |oil
      |blood
      |touch
      |grew
      |cent
      |mix
      |team
      |wire
      |cost
      |lost
      |brown
      |wear
      |garden
      |equal
      |sent
      |choose
      |fell
      |fit
      |flow
      |fair
      |bank
      |collect
      |save
      |control
      |decimal
      |gentle
      |woman
      |captain
      |practice
      |separate
      |difficult
      |doctor
      |please
      |protect
      |noon
      |whose
      |locate
      |ring
      |character
      |insect
      |caught
      |period
      |indicate
      |radio
      |spoke
      |atom
      |human
      |history
      |effect
      |electric
      |expect
      |crop
      |modern
      |element
      |hit
      |student
      |corner
      |party
      |supply
      |bone
      |rail
      |imagine
      |provide
      |agree
      |thus
      |capital
      |won't
      |chair
      |danger
      |fruit
      |rich
      |thick
      |soldier
      |process
      |operate
      |guess
      |necessary
      |sharp
      |wing
      |create
      |neighbor
      |wash
      |bat
      |rather
      |crowd
      |corn
      |compare
      |poem
      |string
      |bell
      |depend
      |meat
      |rub
      |tube
      |famous
      |dollar
      |stream
      |fear
      |sight
      |thin
      |triangle
      |planet
      |hurry
      |chief
      |colony
      |clock
      |mine
      |tie
      |enter
      |major
      |fresh
      |search
      |send
      |yellow
      |gun
      |allow
      |print
      |dead
      |spot
      |desert
      |suit
      |current
      |lift
      |rose
      |continue
      |block
      |chart
      |hat
      |sell
      |success
      |company
      |subtract
      |event
      |particular
      |deal
      |swim
      |term
      |opposite
      |wife
      |shoe
      |shoulder
      |spread
      |arrange
      |camp
      |invent
      |cotton
      |born
      |determine
      |quart
      |nine
      |truck
      |noise
      |level
      |chance
      |gather
      |shop
      |stretch
      |throw
      |shine
      |property
      |column
      |molecule
      |select
      |wrong
      |gray
      |repeat
      |require
      |broad
      |prepare
      |salt
      |nose
      |plural
      |anger
      |claim
      |continent
      |oxygen
      |sugar
      |death
      |pretty
      |skill
      |women
      |season
      |solution
      |magnet
      |silver
      |thank
      |branch
      |match
      |suffix
      |especially
      |fig
      |afraid
      |huge
      |sister
      |steel
      |discuss
      |forward
      |similar
      |guide
      |experience
      |score
      |apple
      |bought
      |led
      |pitch
      |coat
      |mass
      |card
      |band
      |rope
      |slip
      |win
      |dream
      |evening
      |condition
      |feed
      |tool
      |total
      |basic
      |smell
      |valley
      |nor
      |double
      |seat
      |arrive
      |master
      |track
      |parent
      |shore
      |division
      |sheet
      |substance
      |favor
      |connect
      |post
      |spend
      |chord
      |fat
      |glad
      |original
      |share
      |station
      |dad
      |bread
      |charge
      |proper
      |bar
      |offer
      |segment
      |slave
      |duck
      |instant
      |market
      |degree
      |populate
      |chick
      |dear
      |enemy
      |reply
      |drink
      |occur
      |support
      |speech
      |nature
      |range
      |steam
      |motion
      |path
      |liquid
      |log
      |meant
      |quotient
      |teeth
      |shell
      |neck
      |""".stripMargin.split("\n").map(_.toLowerCase).toSet

  val frenchWordsSet: Set[String] =
    """
      |comme
      |je
      |son
      |que
      |il
      |était
      |pour
      |sur
      |sont
      |avec
      |ils
      |être
      |à
      |un
      |avoir
      |ce
      |à partir de
      |par
      |chaud
      |mot
      |mais
      |que
      |certains
      |est
      |il
      |vous
      |ou
      |eu
      |la
      |de
      |à
      |et
      |un
      |dans
      |nous
      |boîte
      |dehors
      |autre
      |étaient
      |qui
      |faire
      |leur
      |temps
      |si
      |volonté
      |comment
      |dit
      |un
      |chaque
      |dire
      |ne
      |ensemble
      |trois
      |vouloir
      |air
      |bien
      |aussi
      |jouer
      |petit
      |fin
      |mettre
      |maison
      |lire
      |main
      |port
      |grand
      |épeler
      |ajouter
      |même
      |terre
      |ici
      |il faut
      |grand
      |haut
      |tel
      |suivre
      |acte
      |pourquoi
      |interroger
      |hommes
      |changement
      |est allé
      |lumière
      |genre
      |de
      |besoin
      |maison
      |image
      |essayer
      |nous
      |encore
      |animal
      |point
      |mère
      |monde
      |près de
      |construire
      |soi
      |terre
      |père
      |tout
      |nouveau
      |travail
      |partie
      |prendre
      |obtenir
      |lieu
      |fabriqué
      |vivre
      |où
      |après
      |arrière
      |peu
      |seulement
      |tour
      |homme
      |année
      |est venu
      |montrer
      |tous
      |bon
      |moi
      |donner
      |notre
      |sous
      |nom
      |très
      |par
      |juste
      |forme
      |phrase
      |grand
      |penser
      |dire
      |aider
      |faible
      |ligne
      |différer
      |tour
      |la cause
      |beaucoup
      |signifier
      |avant
      |déménagement
      |droit
      |garçon
      |vieux
      |trop
      |même
      |elle
      |tous
      |là
      |quand
      |jusqu’à
      |utiliser
      |votre
      |manière
      |sur
      |beaucoup
      |puis
      |les
      |écrire
      |voudrais
      |comme
      |si
      |ces
      |son
      |long
      |faire
      |chose
      |voir
      |lui
      |deux
      |a
      |regarder
      |plus
      |jour
      |pourrait
      |aller
      |venir
      |fait
      |nombre
      |son
      |aucun
      |plus
      |personnes
      |ma
      |sur
      |savoir
      |eau
      |que
      |appel
      |première
      |qui
      |peut
      |vers le bas
      |côté
      |été
      |maintenant
      |trouver
      |tête
      |supporter
      |propre
      |page
      |devrait
      |pays
      |trouvé
      |réponse
      |école
      |croître
      |étude
      |encore
      |apprendre
      |usine
      |couvercle
      |nourriture
      |soleil
      |quatre
      |entre
      |état
      |garder
      |œil
      |jamais
      |dernier
      |laisser
      |pensée
      |ville
      |arbre
      |traverser
      |ferme
      |dur
      |début
      |puissance
      |histoire
      |scie
      |loin
      |mer
      |tirer
      |gauche
      |tard
      |courir
      |needs a context
      |tandis que
      |presse
      |proche
      |nuit
      |réel
      |vie
      |peu
      |nord
      |livre
      |porter
      |a pris
      |science
      |manger
      |chambre
      |ami
      |a commencé
      |idée
      |poisson
      |montagne
      |Arrêtez
      |une fois
      |base
      |entendre
      |cheval
      |coupe
      |sûr
      |regarder
      |couleur
      |face
      |bois
      |principal
      |ouvert
      |paraître
      |ensemble
      |suivant
      |blanc
      |enfants
      |commencer
      |eu
      |marcher
      |exemple
      |facilité
      |papier
      |groupe
      |toujours
      |musique
      |ceux
      |tous les deux
      |marque
      |souvent
      |lettre
      |jusqu’à ce que
      |mile
      |rivière
      |voiture
      |pieds
      |soins
      |deuxième
      |assez
      |plaine
      |fille
      |habituel
      |jeune
      |prêt
      |au-dessus
      |jamais
      |rouge
      |liste
      |bien que
      |sentir
      |parler
      |oiseau
      |bientôt
      |corps
      |chien
      |famille
      |direct
      |pose
      |laisser
      |chanson
      |mesurer
      |porte
      |produit
      |noir
      |court
      |chiffre
      |classe
      |vent
      |question
      |arriver
      |complète
      |navire
      |zone
      |moitié
      |rock
      |ordre
      |feu
      |sud
      |problème
      |pièce
      |dit
      |savait
      |passer
      |depuis
      |haut
      |ensemble
      |roi
      |rue
      |pouce
      |multiplier
      |rien
      |cours
      |rester
      |roue
      |plein
      |force
      |bleu
      |objet
      |décider
      |surface
      |profond
      |lune
      |île
      |pied
      |système
      |occupé
      |test
      |record
      |bateau
      |commun
      |or
      |possible
      |plan
      |place
      |sec
      |se demander
      |rire
      |mille
      |il ya
      |ran
      |vérifier
      |jeu
      |forme
      |assimiler
      |chaud
      |manquer
      |apporté
      |chaleur
      |neige
      |pneu
      |apporter
      |oui
      |lointain
      |remplir
      |est
      |peindre
      |langue
      |entre
      |unité
      |puissance
      |ville
      |fin
      |certain
      |voler
      |tomber
      |conduire
      |cri
      |sombre
      |machine
      |Note
      |patienter
      |plan
      |figure
      |étoile
      |boîte
      |nom
      |domaine
      |reste
      |correct
      |capable
      |livre
      |Terminé
      |beauté
      |entraînement
      |résisté
      |contenir
      |avant
      |enseigner
      |semaine
      |finale
      |donné
      |vert
      |oh
      |rapide
      |développer
      |océan
      |chaud
      |gratuit
      |minute
      |fort
      |spécial
      |esprit
      |derrière
      |clair
      |queue
      |produire
      |fait
      |espace
      |entendu
      |meilleur
      |heure
      |mieux
      |vrai
      |pendant
      |cent
      |cinq
      |rappeler
      |étape
      |tôt
      |tenir
      |ouest
      |sol
      |intérêt
      |atteindre
      |rapide
      |verbe
      |chanter
      |écouter
      |six
      |table
      |Voyage
      |moins
      |matin
      |dix
      |simple
      |plusieurs
      |voyelle
      |vers
      |guerre
      |poser
      |contre
      |modèle
      |lent
      |centre
      |amour
      |personne
      |argent
      |servir
      |apparaître
      |route
      |carte
      |pluie
      |règle
      |gouverner
      |tirer
      |froid
      |avis
      |voix
      |énergie
      |chasse
      |probable
      |lit
      |frère
      |œuf
      |tour
      |cellule
      |croire
      |peut-être
      |choisir
      |soudain
      |compter
      |carré
      |raison
      |longueur
      |représenter
      |art
      |sujet
      |région
      |taille
      |varier
      |régler
      |parler
      |poids
      |général
      |glace
      |question
      |cercle
      |paire
      |inclure
      |fracture
      |syllabe
      |feutre
      |grandiose
      |balle
      |encore
      |vague
      |tomber
      |cœur
      |h
      |présent
      |lourd
      |danse
      |moteur
      |position
      |bras
      |large
      |voile
      |matériel
      |fraction
      |forêt
      |s’asseoir
      |course
      |fenêtre
      |magasin
      |été
      |train
      |sommeil
      |prouver
      |seul
      |jambe
      |exercice
      |mur
      |capture
      |monture
      |souhaiter
      |ciel
      |conseil
      |joie
      |hiver
      |sat
      |écrit
      |sauvage
      |instrument
      |conservé
      |verre
      |herbe
      |vache
      |emploi
      |bord
      |signe
      |visite
      |passé
      |doux
      |amusement
      |clair
      |gaz
      |temps
      |mois
      |million
      |porter
      |finition
      |heureux
      |espoir
      |fleur
      |vêtir
      |étrange
      |disparu
      |commerce
      |mélodie
      |voyage
      |bureau
      |recevoir
      |rangée
      |bouche
      |exact
      |symbole
      |mourir
      |moins
      |difficulté
      |cri
      |sauf
      |écrit
      |semence
      |ton
      |joindre
      |suggérer
      |propre
      |pause
      |dame
      |cour
      |augmenter
      |mauvais
      |coup
      |huile
      |sang
      |toucher
      |a augmenté
      |cent
      |mélanger
      |équipe
      |fil
      |coût
      |perdu
      |brun
      |porter
      |jardin
      |égal
      |expédié
      |choisir
      |est tombé
      |s’adapter
      |débit
      |juste
      |banque
      |recueillir
      |sauver
      |contrôle
      |décimal
      |oreille
      |autre
      |tout à fait
      |cassé
      |cas
      |milieu
      |tuer
      |fils
      |lac
      |moment
      |échelle
      |fort
      |printemps
      |observer
      |enfant
      |droit
      |consonne
      |nation
      |dictionnaire
      |lait
      |vitesse
      |méthode
      |organe
      |payer
      |âge
      |section
      |robe
      |nuage
      |surprise
      |calme
      |pierre
      |minuscule
      |montée
      |frais
      |conception
      |pauvres
      |lot
      |expérience
      |bas
      |clé
      |fer
      |unique
      |bâton
      |plat
      |vingt
      |peau
      |sourire
      |pli
      |trou
      |sauter
      |bébé
      |huit
      |village
      |se rencontrent
      |racine
      |acheter
      |augmenter
      |résoudre
      |métal
      |si
      |pousser
      |sept
      |paragraphe
      |troisième
      |doit
      |en attente
      |cheveux
      |décrire
      |cuisinier
      |étage
      |chaque
      |résultat
      |brûler
      |colline
      |coffre-fort
      |chat
      |siècle
      |envisager
      |type
      |droit
      |peu
      |côte
      |copie
      |phrase
      |silencieux
      |haut
      |sable
      |sol
      |rouleau
      |température
      |doigt
      |industrie
      |valeur
      |lutte
      |mensonge
      |battre
      |exciter
      |naturel
      |vue
      |sens
      |capital
      |ne sera pas
      |chaise
      |danger
      |fruit
      |riche
      |épais
      |soldat
      |processus
      |fonctionner
      |pratique
      |séparé
      |difficile
      |médecin
      |s’il vous plaît
      |protéger
      |midi
      |récolte
      |moderne
      |élément
      |frapper
      |étudiant
      |coin
      |partie
      |alimentation
      |dont
      |localiser
      |anneau
      |caractère
      |insecte
      |pris
      |période
      |indiquer
      |radio
      |rayon
      |atome
      |humain
      |histoire
      |effet
      |électrique
      |attendre
      |os
      |rail
      |imaginer
      |fournir
      |se mettre d’accord
      |ainsi
      |doux
      |femme
      |capitaine
      |deviner
      |nécessaire
      |net
      |aile
      |créer
      |voisin
      |lavage
      |chauve-souris
      |plutôt
      |foule
      |blé
      |comparer
      |poème
      |chaîne
      |cloche
      |dépendre
      |viande
      |rub
      |tube
      |célèbre
      |dollar
      |courant
      |peur
      |vue
      |mince
      |triangle
      |planète
      |se dépêcher
      |chef
      |colonie
      |horloge
      |mine
      |lien
      |entrer
      |majeur
      |frais
      |recherche
      |envoyer
      |jaune
      |pistolet
      |permettre
      |impression
      |mort
      |place
      |désert
      |costume
      |courant
      |ascenseur
      |rose
      |arriver
      |maître
      |piste
      |mère
      |rivage
      |division
      |feuille
      |substance
      |favoriser
      |relier
      |poste
      |passer
      |corde
      |graisse
      |heureux
      |original
      |part
      |station
      |papa
      |pain
      |charger
      |propre
      |bar
      |proposition
      |segment
      |esclave
      |canard
      |instant
      |marché
      |degré
      |peupler
      |poussin
      |cher
      |ennemi
      |répondre
      |boisson
      |se produire
      |support
      |discours
      |nature
      |gamme
      |vapeur
      |mouvement
      |chemin
      |liquide
      |enregistrer
      |signifiait
      |quotient
      |dents
      |coquille
      |cou
      |oxygène
      |sucre
      |décès
      |assez
      |compétence
      |femmes
      |saison
      |solution
      |aimant
      |argent
      |merci
      |branche
      |rencontre
      |suffixe
      |particulièrement
      |figue
      |peur
      |énorme
      |sœur
      |acier
      |discuter
      |avant
      |similaire
      |guider
      |expérience
      |score
      |pomme
      |acheté
      |LED
      |pas
      |manteau
      |masse
      |carte
      |bande
      |corde
      |glissement
      |gagner
      |rêver
      |soirée
      |condition
      |alimentation
      |outil
      |total
      |de base
      |odeur
      |vallée
      |ni
      |double
      |siège
      |continuer
      |bloc
      |graphique
      |chapeau
      |vendre
      |succès
      |entreprise
      |soustraire
      |événement
      |particulier
      |accord
      |baignade
      |terme
      |opposé
      |femme
      |chaussure
      |épaule
      |propagation
      |organiser
      |camp
      |inventer
      |coton
      |né
      |déterminer
      |litre
      |neuf
      |camion
      |bruit
      |niveau
      |chance
      |recueillir
      |boutique
      |tronçon
      |jeter
      |éclat
      |propriété
      |colonne
      |molécule
      |sélectionner
      |mal
      |gris
      |répétition
      |exiger
      |large
      |préparer
      |sel
      |nez
      |pluriel
      |colère
      |revendication
      |continent…
      |""".stripMargin.split("\n").map(_.toLowerCase).toSet

  val germanWordsSet: Set[String] =
    """
      |wie
      |ich
      |seine
      |dass
      |er
      |war
      |für
      |auf
      |sind
      |mit
      |sie
      |sein
      |bei
      |ein
      |haben
      |dies
      |aus
      |durch
      |heiß
      |Wort
      |aber
      |was
      |einige
      |ist
      |es
      |Sie
      |oder
      |hatte
      |die
      |von
      |zu
      |und
      |ein
      |bei
      |wir
      |können
      |aus
      |andere
      |waren
      |die
      |tun
      |ihre
      |Zeit
      |wenn
      |werden
      |wie
      |sagte
      |ein
      |jeder
      |sagen
      |tut
      |Satz
      |drei
      |wollen
      |Luft
      |gut
      |auch
      |spielen
      |klein
      |Ende
      |setzen
      |Zuhause
      |lesen
      |seits
      |Hafen
      |groß
      |buchstabieren
      |hinzufügen
      |auch
      |Lande
      |hier
      |muss
      |groß
      |hoch
      |so
      |folgen
      |Akt
      |warum
      |fragen
      |Männer
      |Veränderung
      |ging
      |Licht
      |Art
      |aus
      |müssen
      |Haus
      |Bild
      |versuchen
      |uns
      |wieder
      |Tier
      |Punkt
      |Mutter
      |Welt
      |in der Nähe von
      |bauen
      |selbst
      |Erde
      |Vater
      |jeder
      |neu
      |Arbeit
      |Teil
      |nehmen
      |erhalten
      |Ort
      |gemacht
      |leben
      |wo
      |nach
      |zurück
      |wenig
      |nur
      |Runde
      |Mann
      |Jahr
      |kam
      |zeigen
      |jeder
      |gut
      |mir
      |geben
      |unsere
      |unter
      |Name
      |sehr
      |durch
      |nur
      |Formular
      |Satz
      |groß
      |denken
      |sagen
      |Hilfe
      |niedrig
      |Linie
      |abweichen
      |wiederum
      |Ursache
      |viel
      |bedeuten
      |vor
      |Umzug
      |Recht
      |Junge
      |alt
      |zu
      |gleich
      |sie
      |alle
      |da
      |wenn
      |nach oben
      |Verwendung
      |Ihre
      |Weg
      |über
      |viele
      |dann
      |sie
      |schreiben
      |würde
      |wie
      |so
      |diese
      |sie
      |lange
      |machen
      |Sache
      |sehen
      |ihm
      |zwei
      |hat
      |suchen
      |mehr
      |Tag
      |könnte
      |gehen
      |kommen
      |tat
      |Anzahl
      |klingen
      |nicht
      |am meisten
      |Menschen
      |meine
      |über
      |wissen
      |Wasser
      |als
      |Anruf
      |erste
      |die
      |können
      |nach unten
      |Seite
      |gewesen
      |jetzt
      |finden
      |Kopf
      |stehen
      |besitzen
      |Seite
      |sollte
      |Land
      |gefunden
      |Antwort
      |Schule
      |wachsen
      |Studie
      |noch
      |lernen
      |Anlage
      |Abdeckung
      |Lebensmittel
      |Sonne
      |vier
      |zwischen
      |Zustand
      |halten
      |Auge
      |nie
      |letzte
      |lassen
      |Gedanken
      |Stadt
      |Baum
      |überqueren
      |Bauernhof
      |schwer
      |Beginn
      |Macht
      |Geschichte
      |Säge
      |weit
      |Meer
      |ziehen
      |links
      |spät
      |laufen
      |unterlassen Sie
      |während
      |Presse
      |Schließen
      |Nacht
      |realen
      |Leben
      |wenige
      |Norden
      |Buch
      |tragen
      |nahm
      |Wissenschaft
      |essen
      |Zimmer
      |Freund
      |begann
      |Idee
      |Fisch
      |berg
      |Stopp
      |einmal
      |Basis
      |hören
      |Pferd
      |Schnitt
      |sicher
      |beobachten
      |Farbe
      |Gesicht
      |Holz
      |Haupt-
      |geöffnet
      |scheinen
      |zusammen
      |nächste
      |weiß
      |Kinder
      |Start
      |bekam
      |gehen
      |Beispiel
      |erleichtern
      |Papier
      |Gruppe
      |immer
      |Musik
      |diejenigen
      |beide
      |Marke
      |oft
      |Schreiben
      |bis
      |Meile
      |Fluss
      |Auto
      |Füße
      |Pflege
      |zweite
      |genug
      |Ebene
      |Mädchen
      |üblich
      |jung
      |bereit
      |oben
      |je
      |rot
      |Liste
      |obwohl
      |fühlen
      |Vortrag
      |Vogel
      |bald
      |Körper
      |Hund
      |Familie
      |direkt
      |Pose
      |verlassen
      |Lied
      |messen
      |Tür
      |Produkt
      |schwarz
      |kurz
      |Zahl
      |Klasse
      |Wind
      |Frage
      |passieren
      |vollständig
      |Schiff
      |Bereich
      |Hälfte
      |Stein
      |bestellen
      |Feuer
      |Süden
      |Problem
      |Stück
      |sagte
      |wusste
      |passieren
      |seit
      |obere
      |ganze
      |König
      |Straße
      |Zoll
      |multiplizieren
      |nichts
      |Kurs
      |bleiben
      |Rad
      |voll
      |Kraft
      |blau
      |Objekt
      |entscheiden
      |Oberfläche
      |tief
      |Mond
      |Insel
      |Fuß
      |System
      |beschäftigt
      |Prüfung
      |Rekord
      |Boot
      |gemeinsam
      |goldenen
      |möglich
      |Flugzeug
      |statt
      |trocken
      |Wunder
      |Lachen
      |tausend
      |vor
      |lief
      |überprüfen
      |Spiel
      |Form
      |gleichsetzen
      |heiß
      |Fehl
      |gebracht
      |Wärme
      |Schnee
      |Reifen
      |bringen
      |ja
      |entfernt
      |füllen
      |Osten
      |malen
      |Sprache
      |unter
      |Einheit
      |Macht
      |Stadt
      |fein
      |sicher
      |fliegen
      |fallen
      |führen
      |Schrei
      |dunkel
      |Maschine
      |note
      |warten
      |Plan
      |Abbildung
      |Stern
      |Kasten
      |Nomen
      |Feld
      |Rest
      |richtig
      |fähig
      |Pfund
      |getan
      |Schönheit
      |Antriebs
      |stand
      |enthalten
      |Front
      |lehren
      |Woche
      |Finale
      |gab
      |grün
      |oh
      |schnell
      |entwickeln
      |Ozean
      |warme
      |kostenlos
      |Minute
      |stark
      |besondere
      |Geist
      |hinter
      |klar
      |Schwanz
      |produzieren
      |Tatsache
      |Raum
      |gehört
      |beste
      |Stunde
      |besser
      |wahr
      |während
      |hundert
      |fünf
      |merken
      |Schritt
      |früh
      |halten
      |Westen
      |Boden
      |Interesse
      |erreichen
      |schnell
      |Verbum
      |singen
      |hören
      |sechs
      |Tabelle
      |Reise
      |weniger
      |Morgen
      |zehn
      |einfach
      |mehrere
      |Vokal
      |auf
      |Krieg
      |legen
      |gegen
      |Muster
      |schleppend
      |Zentrum
      |Liebe
      |Person
      |Geld
      |dienen
      |erscheinen
      |Straße
      |Karte
      |regen
      |Regel
      |regieren
      |ziehen
      |Kälte
      |Hinweis
      |Stimme
      |Energie
      |Jagd
      |wahrscheinlich
      |Bett
      |Bruder
      |Ei
      |Fahrt
      |Zelle
      |glauben
      |vielleicht
      |pflücken
      |plötzlich
      |zählen
      |Platz
      |Grund
      |Dauer
      |vertreten
      |Kunst
      |Thema
      |Region
      |Größe
      |variieren
      |regeln
      |sprechen
      |Gewicht
      |allgemein
      |Eis
      |Materie
      |Kreis
      |Paar
      |umfassen
      |Kluft
      |Silbe
      |Filz
      |groß
      |Kugel
      |noch
      |Welle
      |fallen
      |Herz
      |Uhr
      |vorhanden
      |schwer
      |Tanz
      |Motor
      |Position
      |Arm
      |breit
      |Segel
      |Material
      |Fraktion
      |Wald
      |sitzen
      |Rennen
      |Fenster
      |Speicher
      |Sommer
      |Zug
      |Schlaf
      |beweisen
      |einsam
      |Bein
      |Übung
      |Wand
      |Fang
      |Berg
      |wünschen
      |Himmel
      |Board
      |Freude
      |Winter
      |sa
      |geschrieben
      |wilden
      |Instrument
      |gehalten
      |Glas
      |Gras
      |Kuh
      |Arbeit
      |Rand
      |Zeichen
      |Besuch
      |Vergangenheit
      |weich
      |Spaß
      |hell
      |Gases
      |Wetter
      |Monat
      |Million
      |tragen
      |Finish
      |glücklich
      |hoffen
      |blume
      |kleiden
      |seltsam
      |Vorbei
      |Handel
      |Melodie
      |Reise
      |Büro
      |empfangen
      |Reihe
      |Mund
      |genau
      |Zeichen
      |sterben
      |am wenigsten
      |Ärger
      |Schrei
      |außer
      |schrieb
      |Samen
      |Ton
      |beitreten
      |vorschlagen
      |sauber
      |Pause
      |Dame
      |Hof
      |steigen
      |schlecht
      |Schlag
      |Öl
      |Blut
      |berühren
      |wuchs
      |Cent
      |mischen
      |Mannschaft
      |Draht
      |Kosten
      |verloren
      |braun
      |tragen
      |Garten
      |gleich
      |gesendet
      |wählen
      |fiel
      |passen
      |fließen
      |Messe
      |Bank
      |sammeln
      |sparen
      |Kontrolle
      |dezimal
      |Ohr
      |sonst
      |ganz
      |pleite
      |Fall
      |Mitte
      |töten
      |Sohn
      |See
      |Moment
      |Maßstab
      |laut
      |Frühling
      |beobachten
      |Kind
      |gerade
      |Konsonant
      |Nation
      |Wörterbuch
      |milch
      |Geschwindigkeit
      |Verfahren
      |Orgel
      |zahlen
      |Alter
      |Abschnitt
      |Kleid
      |Wolke
      |Überraschung
      |ruhig
      |Stein
      |winzig
      |Aufstieg
      |kühlen
      |Entwurf
      |arm
      |Menge
      |Versuch
      |Boden
      |Schlüssel
      |Eisen
      |Einzel
      |Stick
      |Wohnung
      |zwanzig
      |Haut
      |Lächeln
      |Falte
      |Loch
      |springen
      |Kind
      |acht
      |Dorf
      |treffen
      |Wurzel
      |kaufen
      |erhöhen
      |lösen
      |Metall
      |ob
      |drücken
      |sieben
      |Absatz
      |dritte
      |wird
      |Hand
      |Haar
      |beschreiben
      |Koch
      |Boden
      |entweder
      |Ergebnis
      |brennen
      |Hügel
      |sicher
      |Katze
      |Jahrhundert
      |betrachten
      |Typ
      |Gesetz
      |Bit
      |Küste
      |Kopie
      |Ausdruck
      |still
      |hoch
      |Sand
      |Boden
      |Rolle
      |Temperatur
      |Finger
      |Industrie
      |Wert
      |Kampf
      |Lüge
      |schlagen
      |begeistern
      |natürlich
      |Blick
      |Sinn
      |Hauptstadt
      |wird nicht
      |Stuhl
      |Achtung
      |Obst
      |reich
      |dick
      |Soldat
      |Prozess
      |betreiben
      |Praxis
      |trennen
      |schwierig
      |Arzt
      |Bitte
      |schützen
      |Mittag
      |Ernte
      |modernen
      |Elementes
      |treffen
      |Schüler
      |Ecke
      |Partei
      |Versorgung
      |deren
      |lokalisieren
      |Rings
      |Charakter
      |insekt
      |gefangen
      |Zeit
      |zeigen
      |Funk
      |Speiche
      |Atom
      |Mensch
      |Geschichte
      |Wirkung
      |elektrisch
      |erwarten
      |Knochen
      |Schiene
      |vorstellen
      |bieten
      |zustimmen
      |so
      |sanft
      |Frau
      |Kapitän
      |erraten
      |erforderlich
      |scharf
      |Flügel
      |schaffen
      |Nachbar
      |Wasch
      |Fledermaus
      |eher
      |Menge
      |mais
      |vergleichen
      |Gedicht
      |Schnur
      |Glocke
      |abhängen
      |Fleisch
      |einreiben
      |Rohr
      |berühmt
      |Dollar
      |Strom
      |Angst
      |Blick
      |dünn
      |Dreieck
      |Erde
      |Eile
      |Chef
      |Kolonie
      |Uhr
      |Mine
      |Krawatte
      |eingeben
      |Dur
      |frisch
      |Suche
      |senden
      |gelb
      |Pistole
      |erlauben
      |Druck
      |tot
      |Stelle
      |Wüste
      |Anzug
      |Strom
      |Aufzug
      |stiegen
      |ankommen
      |Stamm
      |Spur
      |Elternteil
      |Ufer
      |Teilung
      |Blatt
      |Substanz
      |begünstigen
      |verbinden
      |nach
      |verbringen
      |Akkord
      |Fett
      |froh
      |Original
      |Aktie
      |Station
      |Papa
      |Brot
      |aufladen
      |richtig
      |Leiste
      |Angebot
      |Segment
      |Sklave
      |ente
      |Augenblick
      |Markt
      |Grad
      |besiedeln
      |küken
      |liebe
      |Feind
      |antworten
      |Getränk
      |auftreten
      |Unterstützung
      |Rede
      |Natur
      |Angebot
      |Dampf
      |Bewegung
      |Weg
      |Flüssigkeit
      |protokollieren
      |gemeint
      |Quotient
      |Gebiss
      |Schale
      |Hals
      |Sauerstoff
      |Zucker
      |Tod
      |ziemlich
      |Geschicklichkeit
      |Frauen
      |Saison
      |Lösung
      |Magnet
      |Silber
      |danken
      |Zweig
      |Spiel
      |Suffix
      |insbesondere
      |Feige
      |ängstlich
      |riesig
      |Schwester
      |Stahl
      |diskutieren
      |vorwärts
      |ähnlich
      |führen
      |Erfahrung
      |Partitur
      |apfel
      |gekauft
      |geführt
      |Tonhöhe
      |Mantel
      |Masse
      |Karte
      |Band
      |Seil
      |Rutsch
      |gewinnen
      |träumen
      |Abend
      |Zustand
      |Futtermittel
      |Werkzeug
      |gesamt
      |Basis
      |Geruch
      |Tal
      |noch
      |doppelt
      |Sitz
      |fortsetzen
      |Block
      |Tabelle
      |Hut
      |verkaufen
      |Erfolg
      |Firma
      |subtrahieren
      |Veranstaltung
      |besondere
      |viel
      |schwimmen
      |Begriff
      |Gegenteil
      |Frau
      |Schuh
      |Schulter
      |Verbreitung
      |arrangieren
      |Lager
      |erfinden
      |Baumwolle
      |geboren
      |bestimmen
      |Quart
      |neun
      |Lastwagen
      |Lärm
      |Ebene
      |Chance
      |sammeln
      |Geschäft
      |Stretch
      |werfen
      |Glanz
      |Immobilien
      |Spalte
      |Molekül
      |wählen
      |falsch
      |grau
      |Wiederholung
      |erfordern
      |breit
      |vorbereiten
      |Salz
      |Nase
      |mehreren
      |Zorn
      |Anspruch
      |Kontinent
      |""".stripMargin.split("\n").map(_.toLowerCase).toSet
}
